# Generated by Django 3.2.6 on 2021-08-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки'),
        ),
    ]
