# Generated by Django 3.2.6 on 2021-08-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0002_alter_score_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_class',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
