# Generated by Django 3.2.5 on 2021-07-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0003_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
