# Generated by Django 3.2.6 on 2021-08-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_visit',
        ),
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний визит'),
        ),
    ]
