# Generated by Django 3.2.6 on 2021-08-18 12:41

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0004_alter_user_is_in_class'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='score',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
