# Generated by Django 3.2.5 on 2021-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0004_user_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teacher',
            field=models.BooleanField(default=False, verbose_name='Учитель?'),
        ),
    ]
