# Generated by Django 3.2.6 on 2021-08-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0005_alter_score_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='score',
            managers=[
            ],
        ),
    ]
