# Generated by Django 3.2.5 on 2021-07-15 12:59

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0005_alter_user_teacher'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('people', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
