# Generated by Django 3.2.5 on 2021-07-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
