# Generated by Django 3.2.6 on 2021-08-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0006_auto_20210817_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
