# Generated by Django 3.2.5 on 2021-07-16 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0008_auto_20210716_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyclass',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='studyclass',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_for_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
    ]
