# Generated by Django 3.2.5 on 2021-07-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0009_auto_20210716_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.BooleanField(default=False, verbose_name='Учитель?'),
        ),
    ]
