# Generated by Django 3.2.5 on 2021-07-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0010_user_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teacher',
        ),
    ]
