# Generated by Django 3.2.6 on 2021-08-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0013_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(null=True, verbose_name='Последний визит'),
        ),
    ]
