# Generated by Django 3.2.6 on 2021-08-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnevnik', '0014_user_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний визит'),
        ),
    ]
